version: '3.8'

services:

  triton:
    container_name: fast_api
    build:
      context: .
      dockerfile: app/Dockerfile 
    volumes:
      - /triton:/triton
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

  backend:
    container_name: fast_api
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    
  
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge