version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile.fastapi
    ports:
      - "8080:8080"
    volumes:
      - ./backend/app:/code/app
      - ./backend/triton:/code/triton
      - ./backend/utils:/code/utils
    environment:
      - PYTHONPATH=/code:/code/app:/code/triton
    depends_on:
      - triton
    networks:
      - ml-network

  streamlit:
    build:
      context: .
      dockerfile: frontend/Dockerfile.streamlit
    ports:
      - "8501:8501"
    networks:
      - ml-network
    depends_on:
      - fastapi

  triton:
    build:
      context: .
      dockerfile: backend/triton/Dockerfile
    volumes:
      - ./models:/models
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
