name: Linter Checking

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Ruff linter
        run: |
          poetry run ruff check notebooks
          poetry run ruff check workflows
      - name: Mypy analyse
        run:  |
          poetry run nbqa mypy notebooks
          poetry run mypy workflows
